name: Linux Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch:

          # - develop

          # main linux distros
          - centos
          - debian
          - fedora
          - opensuse
          - oracle
          - slackware
          - ubuntu

          # zip beta releases
          - '3.1a'
          - '3.1b'
          - '3.1c'
          - '3.1d'
          # doesn't build
          # - '3.1e21'
          # hash below is e14
          - '170645c64912952040642d94b40017b48b9b875d'

          # other forks

    name: Build with '${{ matrix.branch }}''
    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}

    - name: Configure & build
      run: make -f unix/Makefile generic

    - name: Run zip -v
      run: ./zip -v
